import { defineStore } from 'pinia';
import { reactive, ref } from 'vue';
import {
  reqIncomeTotal,
  reqBusinessTotal,
  reqPerformanceTotal,
  reqRechargeTotal,
  reqProductTotal,
  reqProjectTotal,
} from '@/api/home/index';
import { parseResList, parseResObj, parseResMsg } from '@/utils/parseResponse';

export const useHomeStore = defineStore('Home', () => {
  const searchParams = reactive({ startTime: '', endTime: '' });
  const resetSearchParams = () => {
    searchParams.startTime = '';
    searchParams.endTime = '';
  };

  const projectPerformanceData = ref([
    { name: '卡销业务', value: 170603.84 },
    { name: '微信', value: 23066 },
    { name: '支付宝', value: 6918 },
    { name: '银行卡', value: 61746.23 },
    { name: '现金', value: 2067 },
    { name: '电子券', value: 17042.24 },
    { name: '实体券', value: 5023 },
    { name: '美团', value: 21807.4 },
    { name: '抖音', value: 4791.7 },
  ]);
  const rechargeData = ref([
    { name: '微信', value: 23066 },
    { name: '支付宝', value: 6918 },
    { name: '银行卡', value: 61746.23 },
    { name: '现金', value: 2067 },
    { name: '美团', value: 21807.4 },
    { name: '抖音', value: 4791.7 },
  ]);

  const incomeData = ref([
    { name: '微信', value: 188407, itemStyle: { color: '#07C160' } },
    { name: '银行卡', value: 61831.23, itemStyle: { color: '#1485EE' } },
    { name: '支付宝', value: 6918, itemStyle: { color: '#1677FF' } },
    { name: '现金', value: 5567, itemStyle: { color: '#FF9D2B' } },
    { name: '其他', value: 0, itemStyle: { color: '#8C8C8C' } },
  ]);

  const performanceData = ref([
    { name: '应收', value: 85200, itemStyle: { color: '#5B8FF9' } },
    { name: '优惠', value: 67800, itemStyle: { color: '#5AD8A6' } },
    { name: '优惠后金额', value: 42500, itemStyle: { color: '#5D7092' } },
  ]);

  const businessData = ref([
    { name: '点钟', value: 1250, itemStyle: { color: '#C9C9C9' } },
    { name: '加钟', value: 680, itemStyle: { color: '#C0C0C0' } },
    { name: '轮牌', value: 320, itemStyle: { color: '#FFD700' } },
  ]);

  const data = {
    itemStatSummary: {
      statType: 69,
      lunNum: 2316,
      dianNum: 595,
      jiaNum: 1309,
      countNum: 4232,
      countAmount: 295705.49,
      productStatDetails: [
        {
          productId: 107188,
          prodName: '精品采耳',
          prodCode: '102',
          lunNum: 677,
          dianNum: 213,
          jiaNum: 136,
          countNum: 1027,
          countAmount: 58843.24,
        },
        {
          productId: 185491,
          prodName: '代做耳护',
          prodCode: '605',
          lunNum: 0,
          dianNum: 3,
          jiaNum: 37,
          countNum: 40,
          countAmount: 0,
        },
        {
          productId: 205273,
          prodName: 'A精品采耳',
          prodCode: '701',
          lunNum: 283,
          dianNum: 60,
          jiaNum: 31,
          countNum: 374,
          countAmount: 15144.42,
        },
        {
          productId: 191145,
          prodName: '经络疏通40分钟',
          prodCode: '607',
          lunNum: 23,
          dianNum: 31,
          jiaNum: 75,
          countNum: 129,
          countAmount: 12615.82,
        },
        {
          productId: 107208,
          prodName: '经典足疗',
          prodCode: '112',
          lunNum: 203,
          dianNum: 34,
          jiaNum: 92,
          countNum: 330,
          countAmount: 19916.33,
        },
        {
          productId: 107186,
          prodName: '精品修脚',
          prodCode: '101',
          lunNum: 202,
          dianNum: 22,
          jiaNum: 71,
          countNum: 296,
          countAmount: 11002.15,
        },
        {
          productId: 107202,
          prodName: '开背刮痧',
          prodCode: '109',
          lunNum: 3,
          dianNum: 0,
          jiaNum: 33,
          countNum: 36,
          countAmount: 2247.54,
        },
        {
          productId: 107214,
          prodName: '精油开背',
          prodCode: '602',
          lunNum: 55,
          dianNum: 32,
          jiaNum: 127,
          countNum: 214,
          countAmount: 18567.02,
        },
        {
          productId: 107216,
          prodName: '耳部护理',
          prodCode: '601',
          lunNum: 7,
          dianNum: 6,
          jiaNum: 92,
          countNum: 106,
          countAmount: 10329.8,
        },
        {
          productId: 126709,
          prodName: '特色套餐',
          prodCode: '203',
          lunNum: 9,
          dianNum: 1,
          jiaNum: 0,
          countNum: 10,
          countAmount: 1550.04,
        },
        {
          productId: 107212,
          prodName: '局部按摩',
          prodCode: '119',
          lunNum: 76,
          dianNum: 25,
          jiaNum: 97,
          countNum: 198,
          countAmount: 11769.52,
        },
        {
          productId: 107196,
          prodName: '洗眼',
          prodCode: '106',
          lunNum: 6,
          dianNum: 7,
          jiaNum: 39,
          countNum: 53,
          countAmount: 3148.48,
        },
        {
          productId: 107190,
          prodName: '头疗',
          prodCode: '103',
          lunNum: 21,
          dianNum: 11,
          jiaNum: 88,
          countNum: 121,
          countAmount: 7654.48,
        },
        {
          productId: 198967,
          prodName: '耳部护理三送一',
          prodCode: '608',
          lunNum: 1,
          dianNum: 6,
          jiaNum: 27,
          countNum: 34,
          countAmount: 8553.84,
        },
        {
          productId: 184569,
          prodName: '水洗头疗',
          prodCode: '208',
          lunNum: 73,
          dianNum: 12,
          jiaNum: 55,
          countNum: 140,
          countAmount: 10830.96,
        },
        {
          productId: 126705,
          prodName: 'A套餐',
          prodCode: '201',
          lunNum: 91,
          dianNum: 32,
          jiaNum: 19,
          countNum: 142,
          countAmount: 14559.32,
        },
        {
          productId: 126719,
          prodName: '套餐五选二',
          prodCode: '206',
          lunNum: 249,
          dianNum: 28,
          jiaNum: 6,
          countNum: 283,
          countAmount: 28085.24,
        },
        {
          productId: 126707,
          prodName: '经典套餐',
          prodCode: '202',
          lunNum: 25,
          dianNum: 7,
          jiaNum: 3,
          countNum: 35,
          countAmount: 4512,
        },
        {
          productId: 205307,
          prodName: 'A经典足浴',
          prodCode: '718',
          lunNum: 27,
          dianNum: 1,
          jiaNum: 14,
          countNum: 43,
          countAmount: 2719.08,
        },
        {
          productId: 205503,
          prodName: 'A禅洗头疗',
          prodCode: '719',
          lunNum: 12,
          dianNum: 2,
          jiaNum: 1,
          countNum: 15,
          countAmount: 1432.24,
        },
        {
          productId: 205305,
          prodName: 'A精品修脚',
          prodCode: '717',
          lunNum: 24,
          dianNum: 0,
          jiaNum: 2,
          countNum: 26,
          countAmount: 962.64,
        },
        {
          productId: 205293,
          prodName: 'A水洗头疗',
          prodCode: '711',
          lunNum: 43,
          dianNum: 4,
          jiaNum: 20,
          countNum: 67,
          countAmount: 5165.36,
        },
        {
          productId: 205279,
          prodName: 'A耳浴套餐',
          prodCode: '704',
          lunNum: 26,
          dianNum: 2,
          jiaNum: 1,
          countNum: 29,
          countAmount: 2775,
        },
        {
          productId: 107231,
          prodName: '腹部理疗',
          prodCode: '603',
          lunNum: 1,
          dianNum: 10,
          jiaNum: 27,
          countNum: 38,
          countAmount: 2939.4,
        },
        {
          productId: 107192,
          prodName: '洗耳',
          prodCode: '104',
          lunNum: 3,
          dianNum: 0,
          jiaNum: 55,
          countNum: 58,
          countAmount: 3328.35,
        },
        {
          productId: 107204,
          prodName: '开背拔罐',
          prodCode: '110',
          lunNum: 3,
          dianNum: 0,
          jiaNum: 31,
          countNum: 34,
          countAmount: 2148.32,
        },
        {
          productId: 205281,
          prodName: 'A耳目一新',
          prodCode: '705',
          lunNum: 2,
          dianNum: 0,
          jiaNum: 0,
          countNum: 2,
          countAmount: 195,
        },
        {
          productId: 126721,
          prodName: '套餐五选三',
          prodCode: '207',
          lunNum: 21,
          dianNum: 4,
          jiaNum: 0,
          countNum: 25,
          countAmount: 3948.64,
        },
        {
          productId: 133865,
          prodName: '特价洗面刮脸',
          prodCode: '210',
          lunNum: 22,
          dianNum: 5,
          jiaNum: 30,
          countNum: 57,
          countAmount: 5288.74,
        },
        {
          productId: 205277,
          prodName: 'A耳部护理',
          prodCode: '703',
          lunNum: 1,
          dianNum: 2,
          jiaNum: 22,
          countNum: 25,
          countAmount: 2680.24,
        },
        {
          productId: 205295,
          prodName: 'A局部按摩',
          prodCode: '712',
          lunNum: 4,
          dianNum: 0,
          jiaNum: 4,
          countNum: 8,
          countAmount: 568.62,
        },
        {
          productId: 205275,
          prodName: 'A洗耳',
          prodCode: '702',
          lunNum: 2,
          dianNum: 0,
          jiaNum: 3,
          countNum: 5,
          countAmount: 248.82,
        },
        {
          productId: 126711,
          prodName: '养生套餐',
          prodCode: '204',
          lunNum: 8,
          dianNum: 2,
          jiaNum: 0,
          countNum: 10,
          countAmount: 1524.6,
        },
        {
          productId: 134175,
          prodName: '特价采耳眼部瑜伽',
          prodCode: '211',
          lunNum: 4,
          dianNum: 7,
          jiaNum: 0,
          countNum: 11,
          countAmount: 968,
        },
        {
          productId: 197255,
          prodName: '禅洗头疗',
          prodCode: '209',
          lunNum: 38,
          dianNum: 11,
          jiaNum: 15,
          countNum: 64,
          countAmount: 6700.84,
        },
        {
          productId: 107210,
          prodName: '临时品项',
          prodCode: '118',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 5,
          countAmount: 246.86,
        },
        {
          productId: 107194,
          prodName: '洗面',
          prodCode: '105',
          lunNum: 3,
          dianNum: 3,
          jiaNum: 7,
          countNum: 13,
          countAmount: 869.92,
        },
        {
          productId: 126715,
          prodName: '至尊套餐',
          prodCode: '205',
          lunNum: 6,
          dianNum: 0,
          jiaNum: 1,
          countNum: 7,
          countAmount: 1591.32,
        },
        {
          productId: 205283,
          prodName: 'A耳脑SPA',
          prodCode: '706',
          lunNum: 19,
          dianNum: 3,
          jiaNum: 0,
          countNum: 22,
          countAmount: 2091.04,
        },
        {
          productId: 183879,
          prodName: '上门费',
          prodCode: '604',
          lunNum: 1,
          dianNum: 0,
          jiaNum: 3,
          countNum: 4,
          countAmount: 400,
        },
        {
          productId: 205287,
          prodName: 'A银珠洗眼',
          prodCode: '708',
          lunNum: 1,
          dianNum: 1,
          jiaNum: 3,
          countNum: 5,
          countAmount: 344,
        },
        {
          productId: 205299,
          prodName: 'A精油开背',
          prodCode: '714',
          lunNum: 26,
          dianNum: 3,
          jiaNum: 15,
          countNum: 44,
          countAmount: 3641.2,
        },
        {
          productId: 205291,
          prodName: 'A面护修面',
          prodCode: '710',
          lunNum: 6,
          dianNum: 0,
          jiaNum: 5,
          countNum: 11,
          countAmount: 929,
        },
        {
          productId: 205301,
          prodName: 'A开背刮痧',
          prodCode: '715',
          lunNum: 3,
          dianNum: 0,
          jiaNum: 2,
          countNum: 5,
          countAmount: 381.42,
        },
        {
          productId: 107200,
          prodName: '淋巴排毒',
          prodCode: '108',
          lunNum: 0,
          dianNum: 1,
          jiaNum: 2,
          countNum: 3,
          countAmount: 180.4,
        },
        {
          productId: 205285,
          prodName: 'A头部SPA',
          prodCode: '707',
          lunNum: 0,
          dianNum: 1,
          jiaNum: 4,
          countNum: 5,
          countAmount: 334.62,
        },
        {
          productId: 210311,
          prodName: 'A特价刮痧',
          prodCode: '720',
          lunNum: 0,
          dianNum: 2,
          jiaNum: 4,
          countNum: 6,
          countAmount: 59.4,
        },
        {
          productId: 211019,
          prodName: '特价采耳',
          prodCode: '212',
          lunNum: 1,
          dianNum: 0,
          jiaNum: 0,
          countNum: 1,
          countAmount: 33.8,
        },
        {
          productId: 205303,
          prodName: 'A开背拔罐',
          prodCode: '716',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 2,
          countNum: 2,
          countAmount: 117,
        },
        {
          productId: 211081,
          prodName: 'A耳结石',
          prodCode: '721',
          lunNum: 1,
          dianNum: 0,
          jiaNum: 1,
          countNum: 2,
          countAmount: 396,
        },
        {
          productId: 211393,
          prodName: 'A单侧耳护理',
          prodCode: 'A722',
          lunNum: 0,
          dianNum: 1,
          jiaNum: 4,
          countNum: 5,
          countAmount: 341,
        },
        {
          productId: 107218,
          prodName: '耳结石',
          prodCode: '302',
          lunNum: 3,
          dianNum: 0,
          jiaNum: 0,
          countNum: 3,
          countAmount: 548,
        },
        {
          productId: 205289,
          prodName: 'A面部护理',
          prodCode: '709',
          lunNum: 1,
          dianNum: 0,
          jiaNum: 0,
          countNum: 1,
          countAmount: 69.42,
        },
        {
          productId: 211979,
          prodName: '艾灸体验',
          prodCode: '303',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 3,
          countNum: 3,
          countAmount: 207,
        },
      ],
    },
    prodStatSummary: {
      statType: 71,
      lunNum: 0,
      dianNum: 0,
      jiaNum: 0,
      countNum: 492,
      countAmount: 16127,
      productStatDetails: [
        {
          productId: 107126,
          prodName: '一次性工具',
          prodCode: '0001',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 424,
          countAmount: 4285,
        },
        {
          productId: 127227,
          prodName: '通用脚病',
          prodCode: '222',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 18,
          countAmount: 2484,
        },
        {
          productId: 145617,
          prodName: '肤康抑菌颗粒',
          prodCode: '0003',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 2,
          countAmount: 188,
        },
        {
          productId: 184279,
          prodName: '脚钉',
          prodCode: '13',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 4,
          countAmount: 1000,
        },
        {
          productId: 107180,
          prodName: '惠嘉抑菌液',
          prodCode: '03',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 6,
          countAmount: 1194,
        },
        {
          productId: 107166,
          prodName: '铝合金私人定制6件套',
          prodCode: '523',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 7,
          countAmount: 686,
        },
        {
          productId: 180291,
          prodName: '亮嘉抑菌套盒',
          prodCode: '02',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 1,
          countAmount: 399,
        },
        {
          productId: 189441,
          prodName: '灵动膏',
          prodCode: '521',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 5,
          countAmount: 1245,
        },
        {
          productId: 186329,
          prodName: '小热灸',
          prodCode: '15',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 12,
          countAmount: 2888,
        },
        {
          productId: 180821,
          prodName: '足乐膏',
          prodCode: '06',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 5,
          countAmount: 625,
        },
        {
          productId: 181477,
          prodName: '嘉敏消抑菌膏',
          prodCode: '09',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 1,
          countAmount: 199,
        },
        {
          productId: 184275,
          prodName: '甲沟炎',
          prodCode: '11',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 1,
          countAmount: 300,
        },
        {
          productId: 145619,
          prodName: '足乐草本液',
          prodCode: '0004',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 4,
          countAmount: 366,
        },
        {
          productId: 180975,
          prodName: '洁沃硅胶指环套',
          prodCode: '08',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 1,
          countAmount: 69,
        },
        {
          productId: 107128,
          prodName: '倾意舒缓按摩精油100ml',
          prodCode: '503',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 1,
          countAmount: 199,
        },
      ],
    },
    prodTreatSummary: {
      statType: 75,
      lunNum: 0,
      dianNum: 0,
      jiaNum: 0,
      countNum: 1,
      countAmount: 1380,
      productStatDetails: [
        {
          productId: 190235,
          prodName: '1380精油开背20次',
          prodCode: '1380精油开背20次',
          lunNum: 0,
          dianNum: 0,
          jiaNum: 0,
          countNum: 1,
          countAmount: 1380,
        },
      ],
    },
    rechargeStatPerf: {
      rechargeNum: 152,
      countAmount: 168926,
    },
  };

  return {
    projectPerformanceData,
    rechargeData,
    incomeData,
    performanceData,
    businessData,
    data,
  };
});
